spring.application.name=eazystore
server.port=1025
logging.level.root=${LOG_LEVEL:INFO}
logging.file.name=${LOG_FILE_NAME:C:/Users/kittu/Desktop/eazystore-data/logs/app.log}


spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.show-sql =true
spring.jpa.properties.hibernate.format_sql=true
management.endpoint.health.show-details=always
management.endpoints.web.base-path=/eazystore/actuator
management.endpoints.web.exposure.include=*
management.endpoint.configprops.show-values=always
management.endpoint.env.show-values=always
info.app.description=Backend Project for Eazy Store E-commerce application
management.info.env.enabled=true
info.app.name=${spring.application.name}
info.app.version=1.0.0
info.app.contact.email=kittureddy1325@gmail.com
#spring.security.user.name=Ramakrishna
#spring.security.user.password=Kittu@0705
#spring.security.user.roles=USER,ADMIN
spring.sql.init.mode=always

stripe.apiKey=${STRIPE_API_KEY}